bucket_name_source = "final-project-bucket-resource"
storage_class       = "REGIONAL"
project_id          = "fiery-catwalk-440706-k8"
folder_path         = "../../upload"
region              = "us-central1"
dataset_id          = "youtube_data"
table_id            = "live_stream_stats"
csv_file_path       = "../upload/stream_stats.csv"
